### PR TITLE
cannot find enum

### PR DESCRIPTION
**Pull request by jasonltaylor**
Demonstrate issue with protobuf plugin.

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks for this repro Jason.

**Comment by mefellows** [comment]
I think this PR might fix the issue: https://github.com/pactflow/pact-protobuf-plugin/pull/31

**Comment by jasonltaylor** [comment]
@mefellows verified fixed with protobuf 0.3.6

**Comment by mefellows** [comment]
Awesome, thanks for confirming 🙏

**Pull request closed without merging**
