### PR TITLE
No color output

### PR DESCRIPTION
**Pull request by stan-confluent**
Addresses https://github.com/pact-foundation/pact-go/issues/340

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks for this! I'd prefer that this is an option on the Log interface, however the FFI doesn't put it there. So this makes sense.

Could you please:

1. Squash your commits
2. Update the commit message to something that aligns to the commit standard (see https://github.com/pact-foundation/pact-go/blob/master/CONTRIBUTING.md).
3. Force push

I'd suggest `feat: allow disabling of coloured log output in Verifier`

The reason is that the commit messages form the basis of our changelog and release notes.

**Comment by stan-confluent** [comment]
Thanks Matt!
After running the tests locally, some pact .json files are changed. Do you want me to also merge those?

**Comment by stan-confluent** [comment]
Squashed the commits

**Comment by YOU54F** [comment]
failures aren't related to this change, its because one of the deps in master doesn't support go vers less than 1.19

I'll get it sorted and do a separate commit to update the pact files 👍🏾

**Comment by stan-confluent** [comment]
@mefellows @YOU54F friendly ping on this PR :)

**Comment by mefellows** [comment]
Thanks, sorry I didn't see the updated commits etc. - merged!

**Pull request merged**
