### PR TITLE
Pact CLI Install Path

### PR DESCRIPTION
**Pull request by r-best**
Adding ability to specify path to Pact CLI for systems where the CLI can't easily be installed

### CODE REVIEW

**Comment by mefellows** [comment]
👋 hi there, I see this is still in DRAFT - would you still like to see this added?

**Comment by r-best** [comment]
I would! I'll switch the branch so it's for `v1.x.x`, the functionality was done last time I worked on this but I need to review your contribution guidelines and make sure I'm good on unit testing and everything else
And suggestions where to start for that?

**Comment by r-best** [comment]
@mefellows this is ready for review, let me know if any changes are needed

**Comment by r-best** [comment]
@mefellows any update on this?

**Comment by mefellows** [comment]
Apologies, I have one last request - could you please squash and reformat your commit to follow the semantic commit conventions in the developer guide?

Something like 

```
feat: add ability to specify standalone CLI path
```

**Comment by r-best** [comment]
> Apologies, I have one last request - could you please squash and reformat your commit to follow the semantic commit conventions in the developer guide?
> 
> Something like
> 
> ```
> feat: add ability to specify standalone CLI path
> ```

Done! Let me know if anything else is needed 👍

**Comment by mefellows** [comment]
Thanks - released `v1.9.0` 🎉

**Pull request merged**
