### PR TITLE
enhancement: notify if installing on linux with musl library

### PR DESCRIPTION
**Pull request by ramanverma2k**
This PR implements changes to detect if the OS uses musl library and warns the user about possible issues that may occur.

@mefellows could you please review this?

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks!

Apologies, this should be against the `2.x.x` branch - the `master` branch currently works with Alpine. Could you please apply that change to that branch?

**Comment by ramanverma2k** [comment]
Sure thing!

I'll do that as soon as i reach home.

**Comment by ramanverma2k** [comment]
Should i close this PR and make a new one?

**Comment by mefellows** [comment]
Probably easiest!

**Pull request closed without merging**
