### PR TITLE
handle tags for pointers

### PR DESCRIPTION
**Pull request by soniah**

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks @soniah, this is 👍 .

We use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in the repo, which is used to auto-generate release notes. Could you please rebase the change, just rewording your commit?

I'd suggest: `fix: support struct tags for pointers`.

Once that's sorted, i'll merge and release (assuming of course the build passes).

**Comment by soniah** [comment]
No worries. I'll get my internal changes merged and released, then amend this commit. Then do our internal stuff to use the mainline repo.

**Comment by mefellows** [comment]
👍

**Comment by soniah** [comment]
Matt, I've updated the PR title and force pushed.

**Comment by mefellows** [comment]
Sorry to be picky, it's not the PR  title but the commit message that needs updating.

i.e. this:
Screen Shot 2022-02-03 at 2 27 13 pm

should be something like

```
fix: support struct tags for pointers
```

The reason is, the bit before the `:` is used to determine what goes in the changelog.

**Comment by mefellows** [comment]
Also don't worry about the failing build. It looks like I need to update some build dependencies, and i'll do that when I migrate to GH actions (as per the 2.x.x branch). I'll merge this in irrespective, but want you to get the commit recognition :)

**Comment by soniah** [comment]
No worries, done!

**Pull request closed without merging**
