### PR TITLE
Support custom branch

### PR DESCRIPTION
**Pull request by chris-palmer-deltatre**
This PR is to allow the `branch` flag to passed to the underlying pact command when publishing.

### CODE REVIEW

**Comment by mefellows** [comment]
Thanks!

Could you please reword 

> feature: allow branch control within pact-go

to

> feat: allow branch control within pact-go

The specific prefix is important, as we use it to generate changelogs. I'd also suggest including what it does, so my full suggestion is

> feat: support branches when publishing pacts

I'll squash merge this in when that has been done.

**Comment by YOU54F** [comment]
hey @chris-palmer-deltatre

I think this may need to target the `v1.x.x` branch now and the commit message still needs to be updated as per Matt's comment, would you be able to do that? 

If not would you be happy if we did?

@mefellows - Is publishing removed from V2 in favour of using the CLI tools directly?

**Comment by mefellows** [comment]
Thanks Yousaf, that's right. 

I would highly encourage you to use the Pact CLI tooling instead for jobs like this. It has a lot more functionality than we have wrapped up here.

**Comment by mefellows** [comment]
Closing this PR for now, but if you are still interested and can address the above issues, please feel free to re-open.

**Pull request closed without merging**
